path:
  gz_ref_dir: '../reference/data'
  ref_dir: reference
  output: "demo/output"
  bam_tumor: "../demo_data/test"
  bam_normal: "../demo_data/test"

gz_ref:
  fa: "Homo_sapiens_assembly38.fasta.gz"
  interval_list: "S31285117_Padded.list.gz"

ref:
  fa: "Homo_sapiens_assembly38.fasta"
  fai: "Homo_sapiens_assembly38.fasta.fai"
  dict: "Homo_sapiens_assembly38.dict"
  interval_list: "S31285117_Padded.list"
  snp: "Homo_sapiens_assembly38.dbsnp138.vcf"
  snpi: "Homo_sapiens_assembly38.dbsnp138.vcf.idx"
  poly: "Axiom_Exome_Plus.genotypes.all_populations.poly.hg38.vcf.gz"
  polyi: "Axiom_Exome_Plus.genotypes.all_populations.poly.hg38.vcf.gz.tbi"
  hapmap: "hapmap_3.3.hg38.vcf.gz"
  hapmapi: "hapmap_3.3.hg38.vcf.gz.tbi"
  omn: "1000G_omni2.5.hg38.vcf.gz"
  omni: "1000G_omni2.5.hg38.vcf.gz.tbi"
  highsnp: "1000G_phase1.snps.high_confidence.hg38.vcf.gz"
  highsnpi: "1000G_phase1.snps.high_confidence.hg38.vcf.gz.tbi"
  mills: "Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
  millsi: "Mills_and_1000G_gold_standard.indels.hg38.vcf.gz.tbi"

max-gaussians: 2