path:
  output: "path/to/output"
  index_dir: "path/to/resources"
  index_file: "Homo_sapiens_assembly38.fasta.fai"
  bam_tumor: "path/to/bam/tumor"
  bam_normal: "path/to/bam/normal"

controlfreec_params: 
  coefficientOfVariation: 0.062
  threads: 1
