##GATK: v4.2.2.0
import socket
sample_IDs, =glob_wildcards("path/to/BIC_SEQ2/results/{sample}_pvalue.CNVs")
#sample_IDs="DO52556"
# a pseudo-rule that collects the target files
rule all:
	input:
		expand("result/{sample}.seg_vote_by_g2.bed",sample=sample_IDs),
		expand("avinput/{sample}.seg_vote_by_g2.avinput",sample=sample_IDs),
		expand("anno/{sample}.g2.variant_function",sample=sample_IDs),

rule merge_cnv:
	input: 
		bicseq2="path/to/BIC_SEQ2/results/{sample}_pvalue.CNVs",
		dnacopy="path/to/DNAcopy/result/{sample}.CNVs",
		freec_cnv="path/to/freec/result/{sample}.tumor.bam_CNVs",
		freec_median_ratio="path/to/freec/result/{sample}_median_ratio.txt",
		chrlen="resources/hg38_len.txt",
		centromeric="resources/centromeric.txt",
		telomere="resources/telomere.txt"
	output:
		g2="result/{sample}.seg_vote_by_g2.bed",
		e3="result/{sample}.seg_vote_by_3.bed"
	params:
		sample="{sample}",
		output_dir="result",
		expand_len="50000",
		script_dir="tools"
	shell:
		"""
		sh path/to/merge_cnv/run_merge_cnv.sh {params.sample} {input.bicseq2} {input.dnacopy} {input.freec_cnv} {input.freec_median_ratio} {input.chrlen} {input.centromeric} {input.telomere} {params.expand_len} {params.output_dir} {params.script_dir}
		"""
rule convert_to_avinput:
	input:
		g2_cnvs="result/{sample}.seg_vote_by_g2.bed",
		e3_cnvs="result/{sample}.seg_vote_by_3.bed"
	output:
		g2_avinput="avinput/{sample}.seg_vote_by_g2.avinput",
		e3_avinput="avinput/{sample}.seg_vote_by_3.avinput"
	shell:
		"""
		grep -v "start" {input.g2_cnvs} | awk -F '\\t' '{{printf "%s\\t%s\\t%s\\t%s\\t%s\\t%s\\t%s\\t%s\\t%s\\n", $1,$2,$3,0,0,$4,$5,$6,$7}}' > {output.g2_avinput}
		grep -v "start" {input.e3_cnvs} | awk -F '\\t' '{{printf "%s\\t%s\\t%s\\t%s\\t%s\\t%s\\t%s\\t%s\\t%s\\n", $1,$2,$3,0,0,$4,$5,$6,$7}}' > {output.e3_avinput}
		"""
rule annotate:
	input:
		g2_avinput="avinput/{sample}.seg_vote_by_g2.avinput",
		e3_avinput="avinput/{sample}.seg_vote_by_3.avinput"
	output:
		g2_vf="anno/{sample}.g2.variant_function",
		e3_vf="anno/{sample}.e3.variant_function",
	params:
		g2_prefix="anno/{sample}.g2",
		e3_prefix="anno/{sample}.e3",
		humandb="path/to/humandb"
	shell:
		"""
		perl path/to/annovar/annotate_variation.pl -out {params.g2_prefix} -build hg38 {input.g2_avinput} {params.humandb}
		perl path/to/annovar/annotate_variation.pl -out {params.e3_prefix} -build hg38 {input.e3_avinput} {params.humandb}
		"""
