channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.9
  - r-base=4.1.3
  - r-devtools
  - r-seqinr
  - r-mass
  - bioconductor-genomicranges
  - bioconductor-biostrings
  - bioconductor-iranges
  - bioconductor-rsamtools=2.10
  - r-poilog
  - r-dplyr
  - r-ade4
  - bioconductor-genomeinfodb
  - bioconductor-s4vectors
  - bioconductor-genomeinfodbdata
  - r-nlme
  - r-segmented
  - r-plyr
  - samtools
