channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.9
  - r-base
  - r-devtools
  - r-seqinr
  - r-mass
  - bioconductor-genomicranges
  - bioconductor-biostrings
  - bioconductor-iranges
  - bioconductor-rsamtools
  - r-poilog
  - r-dplyr
  - r-ade4
  - bioconductor-genomeinfodb
  - bioconductor-s4vectors
  - r-nlme
  - r-segmented
  - r-plyr
