channels:
  - bioconda
  - conda-forge
dependencies:
  - r-base
  - r-devtools
  - r-seqinr
  - r-mass
  - bioconductor-genomicranges
  - bioconductor-biostrings
  - bioconductor-iranges
  - bioconductor-rsamtools
  - r-poilog
  - r-dplyr
