#xTEA v0.1 for short and linked reads on hg38
import socket
sample_IDs, =glob_wildcards("bam_links_tumor/{sample}.tumor.bam")

rule all:
    input:
        "sample_id.txt",
        "case_ctrl_bam_list.txt",
        "submit_calling_jobs_for_samples.sh",
        expand("working/{sample}/L1/{sample}.tumor_LINE1.vcf",sample=sample_IDs)

rule generate_list:
    input:
        BQSRpath="/storage/douyanmeiLab/TCGA_wu/22_4_6/LZ/BQSRbam"
    output:
        id="sample_id.txt",
        list="case_ctrl_bam_list.txt"
    shell:
        "ls {input.BQSRpath}/tumor/*.bam|grep -o \"LZ-[0-9]*\" >> {output.id}; "
        "paste <(ls {input.BQSRpath}/tumor/*.bam|grep -o \"LZ-[0-9]*\") "
        "<(ls {input.BQSRpath}/tumor/*.bam) "
        "<(ls {input.BQSRpath}/normal/*.bam) >> {output.list}"

rule generate_xTea:
    input:
        id="sample_id.txt",
        list="case_ctrl_bam_list.txt",
        rep_lib="/storage/douyanmeiLab/lujinhong/tools/xTea/rep_lib_annotation/",
        ref="/storage/douyanmeiLab/reference/Homo_sapiens_assembly38.fasta",
        gff3="/storage/douyanmeiLab/lujinhong/resource/gencode.v33.annotation.gff3",
        xtea="/storage/douyanmeiLab/lujinhong/tools/xTea/xtea/",
    output:
        "submit_calling_jobs_for_samples.sh"
    params:
        working="/storage/douyanmeiLab/TCGA_wu/22_4_6/LZ/xtea/working/"
    shell:
        "xtea --case_control --tumor -i {input.id} -b {input.list} -p {params.working} -x null"
        "-o submit_jobs.sh -l {input.rep_lib} -r {input.ref} -g {input.gff3} --xtea {input.xtea} "
        "-y 1 -f 5907 --slurm -t 2-00:00 -q intel-e5,amd_ep2 -n 2 -m 32"

rule run_xTEA:
    input:
        rules.generate_xTea.output
    output:
        "working/{sample}/L1/{sample}.tumor_LINE1.vcf"
    params:
        workspace="/storage/douyanmeiLab/TCGA_wu/22_4_6/LZ/xtea/working/"
    resources:
        mem_mb=25000
    shell:
        "touch {input};"
        "sh run_xTEA.sh {wildcards.sample} {params.workspace}"
