#xTEA v0.1 for short and linked reads on hg38
import socket
sample_IDs, =glob_wildcards("path/to/input/{sample}.tumor.bam")

rule all:
    input:
        expand("/path/to/output/working/{sample}/L1/{sample}.tumor_LINE1.vcf",sample=sample_IDs)

rule generate_list:
    input:
        "path/to/input/bamfile"
    output:
        id="sample_id.txt",
        list="case_ctrl_bam_list.txt"
    shell:
        "ls {input}/*.tumor.bam|sed 's/.tumor.bam//g'|sed 's/.*\///' >> {output.id}; "
        "paste <(ls {input}/*.tumor.bam|sed 's/.tumor.bam//g') "
        "<(ls {input}/*.tumor.bam) "
        "<(ls {input}/*.normal.bam) >> {output.list}"

rule generate_xTea:
    input:
        id="sample_id.txt",
        list="case_ctrl_bam_list.txt",
        rep_lib="resources/rep_lib_annotation/",
        ref="resources/Homo_sapiens_assembly38.fasta",
        gff3="resource/gencode.v33.annotation.gff3",
        xtea="path/to/xTea/xtea/",
    output:
        "path/to/output/working/{sample}/L1/run_xTEA_pipeline.sh"
    params:
        working="path/to/output/working/"
    shell:
        "xtea --case_control --tumor -i {input.id} -b {input.list} -p {params.working} -x null"
        "-o submit_jobs.sh -l {input.rep_lib} -r {input.ref} -g {input.gff3} --xtea {input.xtea} "
        "-y 1 -f 5907 --slurm -t 2-00:00 -q intel-e5,amd_ep2 -n 2 -m 32"

rule run_xTEA:
    input:
        rules.generate_xTea.output
    output:
        "path/to/output/working/{sample}/L1/{sample}.tumor_LINE1.vcf"
    resources:
        mem_mb=25000
    shell:
        "sh {input}"
