channels:
  - eumetsat
  - default
  - conda-forge
  - bioconda
dependencies:
  - python=2.7
  - argparse=1
  - codecov=2
  - mock=2
  - numpy=1.10
  - pysam=0.10
  - scipy=0.17
  - parallel
  - samtools