path:
  ref_dir: "reference"
  gz_ref_dir: '../reference/data'
  output: "demo/output"
  bam_tumor: "../demo_data/test"
  bam_normal: "../demo_data/test"

octopus_param:
  threads: 4

gz_ref:
  fa: "Homo_sapiens_assembly38.fasta.gz"
  interval_list: "S31285117_Padded.list.gz"
  germline: "germline.v0.7.4.forest.gz"
  somatic: "somatic.v0.7.4.forest.gz"

ref:
  fa: "Homo_sapiens_assembly38.fasta"
  fai: "Homo_sapiens_assembly38.fasta.fai"
  dict: "Homo_sapiens_assembly38.dict"
  interval_list: "S31285117_Padded.list"
  germline: "germline.v0.7.4.forest"
  somatic: "somatic.v0.7.4.forest"