##MSIprofier
#This pipeline run MSIprofiler on given bam sample every chromosomes
#Then merge the MSIprofiler result and filter by (p value <0.01)&&(normal reads type <3)
#Get the final as the MSI site
import socket
shell.prefix("module load gcc; source /home/douyanmeiLab/lujinhong/miniconda3/etc/profile.d/conda.sh; conda activate MSIprofiler;")
chrs=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,"X","Y"]
sample_IDs, =glob_wildcards("bam_links_tumor/{sample}.tumor.bam")
#https://github.com/parklab/MSIprofiler

# a pseudo-rule that collects the target files

rule all:
	input:
		expand("result/{sample}/{sample}.chr{chrs}.unphased_unphased.txt",sample=sample_IDs,chrs=chrs),
		expand("MSI/{sample}.unphased_MSI.txt",sample=sample_IDs)

rule unphased_MSIprofiler_1:
	input:
		bam="bam_links_tumor/{sample}.tumor.bam",
		fasta="/storage/douyanmeiLab/lujinhong/tools/MSIprofiler/chrs_fa/",
		reference_set="/storage/douyanmeiLab/lujinhong/tools/MSIprofiler/reference_sets/"
	output:
		"result/{sample}/{sample}.chr1.unphased_unphased.txt"
	resources:
		mem_mb=12000
	shell:
		"python /storage/douyanmeiLab/lujinhong/tools/MSIprofiler/msi_profiler.py "
		"--tumor_bam {input.bam} "
		"--normal_bam bam_links_normal/{wildcards.sample}.normal.bam "
		"--bed None "
		"--chromosomes 1 "
		"--fasta {input.fasta}/ "
		"--output_prefix result/{wildcards.sample}/{wildcards.sample}.chr1.unphased "
		"--mode unphased "
		"--nprocs 2 "
		"--reference_set {input.reference_set}/ "
		"--min_coverage 8 "
		"--min_MS_length 6 "
		"--flank_size 5 "
		"--rus 1 2 3 4 5 6 "

rule unphased_MSIprofiler_2:
	input:
		bam="bam_links_tumor/{sample}.tumor.bam",
		fasta="/storage/douyanmeiLab/lujinhong/tools/MSIprofiler/chrs_fa/",
		reference_set="/storage/douyanmeiLab/lujinhong/tools/MSIprofiler/reference_sets/"
	output:
		"result/{sample}/{sample}.chr2.unphased_unphased.txt"
	resources:
		mem_mb=12000
	shell:
		"python /storage/douyanmeiLab/lujinhong/tools/MSIprofiler/msi_profiler.py "
		"--tumor_bam {input.bam} "
		"--normal_bam bam_links_normal/{wildcards.sample}.normal.bam "
		"--bed None "
		"--chromosomes 2 "
		"--fasta {input.fasta}/ "
		"--output_prefix result/{wildcards.sample}/{wildcards.sample}.chr2.unphased "
		"--mode unphased "
		"--nprocs 2 "
		"--reference_set {input.reference_set}/ "
		"--min_coverage 8 "
		"--min_MS_length 6 "
		"--flank_size 5 "
		"--rus 1 2 3 4 5 6 "

rule unphased_MSIprofiler_3:
	input:
		bam="bam_links_tumor/{sample}.tumor.bam",
		fasta="/storage/douyanmeiLab/lujinhong/tools/MSIprofiler/chrs_fa/",
		reference_set="/storage/douyanmeiLab/lujinhong/tools/MSIprofiler/reference_sets/"
	output:
		"result/{sample}/{sample}.chr3.unphased_unphased.txt"
	resources:
		mem_mb=12000
	shell:
		"python /storage/douyanmeiLab/lujinhong/tools/MSIprofiler/msi_profiler.py "
		"--tumor_bam {input.bam} "
		"--normal_bam bam_links_normal/{wildcards.sample}.normal.bam "
		"--bed None "
		"--chromosomes 3 "
		"--fasta {input.fasta}/ "
		"--output_prefix result/{wildcards.sample}/{wildcards.sample}.chr3.unphased "
		"--mode unphased "
		"--nprocs 2 "
		"--reference_set {input.reference_set}/ "
		"--min_coverage 8 "
		"--min_MS_length 6 "
		"--flank_size 5 "
		"--rus 1 2 3 4 5 6 "

rule unphased_MSIprofiler_4:
	input:
		bam="bam_links_tumor/{sample}.tumor.bam",
		fasta="/storage/douyanmeiLab/lujinhong/tools/MSIprofiler/chrs_fa/",
		reference_set="/storage/douyanmeiLab/lujinhong/tools/MSIprofiler/reference_sets/"
	output:
		"result/{sample}/{sample}.chr4.unphased_unphased.txt"
	resources:
		mem_mb=12000
	shell:
		"python /storage/douyanmeiLab/lujinhong/tools/MSIprofiler/msi_profiler.py "
		"--tumor_bam {input.bam} "
		"--normal_bam bam_links_normal/{wildcards.sample}.normal.bam "
		"--bed None "
		"--chromosomes 4 "
		"--fasta {input.fasta}/ "
		"--output_prefix result/{wildcards.sample}/{wildcards.sample}.chr4.unphased "
		"--mode unphased "
		"--nprocs 2 "
		"--reference_set {input.reference_set}/ "
		"--min_coverage 8 "
		"--min_MS_length 6 "
		"--flank_size 5 "
		"--rus 1 2 3 4 5 6 "

rule unphased_MSIprofiler_5:
	input:
		bam="bam_links_tumor/{sample}.tumor.bam",
		fasta="/storage/douyanmeiLab/lujinhong/tools/MSIprofiler/chrs_fa/",
		reference_set="/storage/douyanmeiLab/lujinhong/tools/MSIprofiler/reference_sets/"
	output:
		"result/{sample}/{sample}.chr5.unphased_unphased.txt"
	resources:
		mem_mb=12000
	shell:
		"python /storage/douyanmeiLab/lujinhong/tools/MSIprofiler/msi_profiler.py "
		"--tumor_bam {input.bam} "
		"--normal_bam bam_links_normal/{wildcards.sample}.normal.bam "
		"--bed None "
		"--chromosomes 5 "
		"--fasta {input.fasta}/ "
		"--output_prefix result/{wildcards.sample}/{wildcards.sample}.chr5.unphased "
		"--mode unphased "
		"--nprocs 2 "
		"--reference_set {input.reference_set}/ "
		"--min_coverage 8 "
		"--min_MS_length 6 "
		"--flank_size 5 "
		"--rus 1 2 3 4 5 6 "

rule unphased_MSIprofiler_6:
	input:
		bam="bam_links_tumor/{sample}.tumor.bam",
		fasta="/storage/douyanmeiLab/lujinhong/tools/MSIprofiler/chrs_fa/",
		reference_set="/storage/douyanmeiLab/lujinhong/tools/MSIprofiler/reference_sets/"
	output:
		"result/{sample}/{sample}.chr6.unphased_unphased.txt"
	resources:
		mem_mb=12000
	shell:
		"python /storage/douyanmeiLab/lujinhong/tools/MSIprofiler/msi_profiler.py "
		"--tumor_bam {input.bam} "
		"--normal_bam bam_links_normal/{wildcards.sample}.normal.bam "
		"--bed None "
		"--chromosomes 6 "
		"--fasta {input.fasta}/ "
		"--output_prefix result/{wildcards.sample}/{wildcards.sample}.chr6.unphased "
		"--mode unphased "
		"--nprocs 2 "
		"--reference_set {input.reference_set}/ "
		"--min_coverage 8 "
		"--min_MS_length 6 "
		"--flank_size 5 "
		"--rus 1 2 3 4 5 6 "

rule unphased_MSIprofiler_7:
	input:
		bam="bam_links_tumor/{sample}.tumor.bam",
		fasta="/storage/douyanmeiLab/lujinhong/tools/MSIprofiler/chrs_fa/",
		reference_set="/storage/douyanmeiLab/lujinhong/tools/MSIprofiler/reference_sets/"
	output:
		"result/{sample}/{sample}.chr7.unphased_unphased.txt"
	resources:
		mem_mb=12000
	shell:
		"python /storage/douyanmeiLab/lujinhong/tools/MSIprofiler/msi_profiler.py "
		"--tumor_bam {input.bam} "
		"--normal_bam bam_links_normal/{wildcards.sample}.normal.bam "
		"--bed None "
		"--chromosomes 7 "
		"--fasta {input.fasta}/ "
		"--output_prefix result/{wildcards.sample}/{wildcards.sample}.chr7.unphased "
		"--mode unphased "
		"--nprocs 2 "
		"--reference_set {input.reference_set}/ "
		"--min_coverage 8 "
		"--min_MS_length 6 "
		"--flank_size 5 "
		"--rus 1 2 3 4 5 6 "

rule unphased_MSIprofiler_8:
	input:
		bam="bam_links_tumor/{sample}.tumor.bam",
		fasta="/storage/douyanmeiLab/lujinhong/tools/MSIprofiler/chrs_fa/",
		reference_set="/storage/douyanmeiLab/lujinhong/tools/MSIprofiler/reference_sets/"
	output:
		"result/{sample}/{sample}.chr8.unphased_unphased.txt"
	resources:
		mem_mb=12000
	shell:
		"python /storage/douyanmeiLab/lujinhong/tools/MSIprofiler/msi_profiler.py "
		"--tumor_bam {input.bam} "
		"--normal_bam bam_links_normal/{wildcards.sample}.normal.bam "
		"--bed None "
		"--chromosomes 8 "
		"--fasta {input.fasta}/ "
		"--output_prefix result/{wildcards.sample}/{wildcards.sample}.chr8.unphased "
		"--mode unphased "
		"--nprocs 2 "
		"--reference_set {input.reference_set}/ "
		"--min_coverage 8 "
		"--min_MS_length 6 "
		"--flank_size 5 "
		"--rus 1 2 3 4 5 6 "

rule unphased_MSIprofiler_9:
	input:
		bam="bam_links_tumor/{sample}.tumor.bam",
		fasta="/storage/douyanmeiLab/lujinhong/tools/MSIprofiler/chrs_fa/",
		reference_set="/storage/douyanmeiLab/lujinhong/tools/MSIprofiler/reference_sets/"
	output:
		"result/{sample}/{sample}.chr9.unphased_unphased.txt"
	resources:
		mem_mb=12000
	shell:
		"python /storage/douyanmeiLab/lujinhong/tools/MSIprofiler/msi_profiler.py "
		"--tumor_bam {input.bam} "
		"--normal_bam bam_links_normal/{wildcards.sample}.normal.bam "
		"--bed None "
		"--chromosomes 9 "
		"--fasta {input.fasta}/ "
		"--output_prefix result/{wildcards.sample}/{wildcards.sample}.chr9.unphased "
		"--mode unphased "
		"--nprocs 2 "
		"--reference_set {input.reference_set}/ "
		"--min_coverage 8 "
		"--min_MS_length 6 "
		"--flank_size 5 "
		"--rus 1 2 3 4 5 6 "

rule unphased_MSIprofiler_10:
	input:
		bam="bam_links_tumor/{sample}.tumor.bam",
		fasta="/storage/douyanmeiLab/lujinhong/tools/MSIprofiler/chrs_fa/",
		reference_set="/storage/douyanmeiLab/lujinhong/tools/MSIprofiler/reference_sets/"
	output:
		"result/{sample}/{sample}.chr10.unphased_unphased.txt"
	resources:
		mem_mb=12000
	shell:
		"python /storage/douyanmeiLab/lujinhong/tools/MSIprofiler/msi_profiler.py "
		"--tumor_bam {input.bam} "
		"--normal_bam bam_links_normal/{wildcards.sample}.normal.bam "
		"--bed None "
		"--chromosomes 10 "
		"--fasta {input.fasta}/ "
		"--output_prefix result/{wildcards.sample}/{wildcards.sample}.chr10.unphased "
		"--mode unphased "
		"--nprocs 2 "
		"--reference_set {input.reference_set}/ "
		"--min_coverage 8 "
		"--min_MS_length 6 "
		"--flank_size 5 "
		"--rus 1 2 3 4 5 6 "

rule unphased_MSIprofiler_11:
	input:
		bam="bam_links_tumor/{sample}.tumor.bam",
		fasta="/storage/douyanmeiLab/lujinhong/tools/MSIprofiler/chrs_fa/",
		reference_set="/storage/douyanmeiLab/lujinhong/tools/MSIprofiler/reference_sets/"
	output:
		"result/{sample}/{sample}.chr11.unphased_unphased.txt"
	resources:
		mem_mb=12000
	shell:
		"python /storage/douyanmeiLab/lujinhong/tools/MSIprofiler/msi_profiler.py "
		"--tumor_bam {input.bam} "
		"--normal_bam bam_links_normal/{wildcards.sample}.normal.bam "
		"--bed None "
		"--chromosomes 11 "
		"--fasta {input.fasta}/ "
		"--output_prefix result/{wildcards.sample}/{wildcards.sample}.chr11.unphased "
		"--mode unphased "
		"--nprocs 2 "
		"--reference_set {input.reference_set}/ "
		"--min_coverage 8 "
		"--min_MS_length 6 "
		"--flank_size 5 "
		"--rus 1 2 3 4 5 6 "

rule unphased_MSIprofiler_12:
	input:
		bam="bam_links_tumor/{sample}.tumor.bam",
		fasta="/storage/douyanmeiLab/lujinhong/tools/MSIprofiler/chrs_fa/",
		reference_set="/storage/douyanmeiLab/lujinhong/tools/MSIprofiler/reference_sets/"
	output:
		"result/{sample}/{sample}.chr12.unphased_unphased.txt"
	resources:
		mem_mb=12000
	shell:
		"python /storage/douyanmeiLab/lujinhong/tools/MSIprofiler/msi_profiler.py "
		"--tumor_bam {input.bam} "
		"--normal_bam bam_links_normal/{wildcards.sample}.normal.bam "
		"--bed None "
		"--chromosomes 12 "
		"--fasta {input.fasta}/ "
		"--output_prefix result/{wildcards.sample}/{wildcards.sample}.chr12.unphased "
		"--mode unphased "
		"--nprocs 2 "
		"--reference_set {input.reference_set}/ "
		"--min_coverage 8 "
		"--min_MS_length 6 "
		"--flank_size 5 "
		"--rus 1 2 3 4 5 6 "

rule unphased_MSIprofiler_13:
	input:
		bam="bam_links_tumor/{sample}.tumor.bam",
		fasta="/storage/douyanmeiLab/lujinhong/tools/MSIprofiler/chrs_fa/",
		reference_set="/storage/douyanmeiLab/lujinhong/tools/MSIprofiler/reference_sets/"
	output:
		"result/{sample}/{sample}.chr13.unphased_unphased.txt"
	resources:
		mem_mb=12000
	shell:
		"python /storage/douyanmeiLab/lujinhong/tools/MSIprofiler/msi_profiler.py "
		"--tumor_bam {input.bam} "
		"--normal_bam bam_links_normal/{wildcards.sample}.normal.bam "
		"--bed None "
		"--chromosomes 13 "
		"--fasta {input.fasta}/ "
		"--output_prefix result/{wildcards.sample}/{wildcards.sample}.chr13.unphased "
		"--mode unphased "
		"--nprocs 2 "
		"--reference_set {input.reference_set}/ "
		"--min_coverage 8 "
		"--min_MS_length 6 "
		"--flank_size 5 "
		"--rus 1 2 3 4 5 6 "

rule unphased_MSIprofiler_14:
	input:
		bam="bam_links_tumor/{sample}.tumor.bam",
		fasta="/storage/douyanmeiLab/lujinhong/tools/MSIprofiler/chrs_fa/",
		reference_set="/storage/douyanmeiLab/lujinhong/tools/MSIprofiler/reference_sets/"
	output:
		"result/{sample}/{sample}.chr14.unphased_unphased.txt"
	resources:
		mem_mb=12000
	shell:
		"python /storage/douyanmeiLab/lujinhong/tools/MSIprofiler/msi_profiler.py "
		"--tumor_bam {input.bam} "
		"--normal_bam bam_links_normal/{wildcards.sample}.normal.bam "
		"--bed None "
		"--chromosomes 14 "
		"--fasta {input.fasta}/ "
		"--output_prefix result/{wildcards.sample}/{wildcards.sample}.chr14.unphased "
		"--mode unphased "
		"--nprocs 2 "
		"--reference_set {input.reference_set}/ "
		"--min_coverage 8 "
		"--min_MS_length 6 "
		"--flank_size 5 "
		"--rus 1 2 3 4 5 6 "

rule unphased_MSIprofiler_15:
	input:
		bam="bam_links_tumor/{sample}.tumor.bam",
		fasta="/storage/douyanmeiLab/lujinhong/tools/MSIprofiler/chrs_fa/",
		reference_set="/storage/douyanmeiLab/lujinhong/tools/MSIprofiler/reference_sets/"
	output:
		"result/{sample}/{sample}.chr15.unphased_unphased.txt"
	resources:
		mem_mb=12000
	shell:
		"python /storage/douyanmeiLab/lujinhong/tools/MSIprofiler/msi_profiler.py "
		"--tumor_bam {input.bam} "
		"--normal_bam bam_links_normal/{wildcards.sample}.normal.bam "
		"--bed None "
		"--chromosomes 15 "
		"--fasta {input.fasta}/ "
		"--output_prefix result/{wildcards.sample}/{wildcards.sample}.chr15.unphased "
		"--mode unphased "
		"--nprocs 2 "
		"--reference_set {input.reference_set}/ "
		"--min_coverage 8 "
		"--min_MS_length 6 "
		"--flank_size 5 "
		"--rus 1 2 3 4 5 6 "

rule unphased_MSIprofiler_16:
	input:
		bam="bam_links_tumor/{sample}.tumor.bam",
		fasta="/storage/douyanmeiLab/lujinhong/tools/MSIprofiler/chrs_fa/",
		reference_set="/storage/douyanmeiLab/lujinhong/tools/MSIprofiler/reference_sets/"
	output:
		"result/{sample}/{sample}.chr16.unphased_unphased.txt"
	resources:
		mem_mb=12000
	shell:
		"python /storage/douyanmeiLab/lujinhong/tools/MSIprofiler/msi_profiler.py "
		"--tumor_bam {input.bam} "
		"--normal_bam bam_links_normal/{wildcards.sample}.normal.bam "
		"--bed None "
		"--chromosomes 16 "
		"--fasta {input.fasta}/ "
		"--output_prefix result/{wildcards.sample}/{wildcards.sample}.chr16.unphased "
		"--mode unphased "
		"--nprocs 2 "
		"--reference_set {input.reference_set}/ "
		"--min_coverage 8 "
		"--min_MS_length 6 "
		"--flank_size 5 "
		"--rus 1 2 3 4 5 6 "

rule unphased_MSIprofiler_17:
	input:
		bam="bam_links_tumor/{sample}.tumor.bam",
		fasta="/storage/douyanmeiLab/lujinhong/tools/MSIprofiler/chrs_fa/",
		reference_set="/storage/douyanmeiLab/lujinhong/tools/MSIprofiler/reference_sets/"
	output:
		"result/{sample}/{sample}.chr17.unphased_unphased.txt"
	resources:
		mem_mb=12000
	shell:
		"python /storage/douyanmeiLab/lujinhong/tools/MSIprofiler/msi_profiler.py "
		"--tumor_bam {input.bam} "
		"--normal_bam bam_links_normal/{wildcards.sample}.normal.bam "
		"--bed None "
		"--chromosomes 17 "
		"--fasta {input.fasta}/ "
		"--output_prefix result/{wildcards.sample}/{wildcards.sample}.chr17.unphased "
		"--mode unphased "
		"--nprocs 2 "
		"--reference_set {input.reference_set}/ "
		"--min_coverage 8 "
		"--min_MS_length 6 "
		"--flank_size 5 "
		"--rus 1 2 3 4 5 6 "

rule unphased_MSIprofiler_18:
	input:
		bam="bam_links_tumor/{sample}.tumor.bam",
		fasta="/storage/douyanmeiLab/lujinhong/tools/MSIprofiler/chrs_fa/",
		reference_set="/storage/douyanmeiLab/lujinhong/tools/MSIprofiler/reference_sets/"
	output:
		"result/{sample}/{sample}.chr18.unphased_unphased.txt"
	resources:
		mem_mb=12000
	shell:
		"python /storage/douyanmeiLab/lujinhong/tools/MSIprofiler/msi_profiler.py "
		"--tumor_bam {input.bam} "
		"--normal_bam bam_links_normal/{wildcards.sample}.normal.bam "
		"--bed None "
		"--chromosomes 18 "
		"--fasta {input.fasta}/ "
		"--output_prefix result/{wildcards.sample}/{wildcards.sample}.chr18.unphased "
		"--mode unphased "
		"--nprocs 2 "
		"--reference_set {input.reference_set}/ "
		"--min_coverage 8 "
		"--min_MS_length 6 "
		"--flank_size 5 "
		"--rus 1 2 3 4 5 6 "

rule unphased_MSIprofiler_19:
	input:
		bam="bam_links_tumor/{sample}.tumor.bam",
		fasta="/storage/douyanmeiLab/lujinhong/tools/MSIprofiler/chrs_fa/",
		reference_set="/storage/douyanmeiLab/lujinhong/tools/MSIprofiler/reference_sets/"
	output:
		"result/{sample}/{sample}.chr19.unphased_unphased.txt"
	resources:
		mem_mb=12000
	shell:
		"python /storage/douyanmeiLab/lujinhong/tools/MSIprofiler/msi_profiler.py "
		"--tumor_bam {input.bam} "
		"--normal_bam bam_links_normal/{wildcards.sample}.normal.bam "
		"--bed None "
		"--chromosomes 19 "
		"--fasta {input.fasta}/ "
		"--output_prefix result/{wildcards.sample}/{wildcards.sample}.chr19.unphased "
		"--mode unphased "
		"--nprocs 2 "
		"--reference_set {input.reference_set}/ "
		"--min_coverage 8 "
		"--min_MS_length 6 "
		"--flank_size 5 "
		"--rus 1 2 3 4 5 6 "

rule unphased_MSIprofiler_20:
	input:
		bam="bam_links_tumor/{sample}.tumor.bam",
		fasta="/storage/douyanmeiLab/lujinhong/tools/MSIprofiler/chrs_fa/",
		reference_set="/storage/douyanmeiLab/lujinhong/tools/MSIprofiler/reference_sets/"
	output:
		"result/{sample}/{sample}.chr20.unphased_unphased.txt"
	resources:
		mem_mb=12000
	shell:
		"python /storage/douyanmeiLab/lujinhong/tools/MSIprofiler/msi_profiler.py "
		"--tumor_bam {input.bam} "
		"--normal_bam bam_links_normal/{wildcards.sample}.normal.bam "
		"--bed None "
		"--chromosomes 20 "
		"--fasta {input.fasta}/ "
		"--output_prefix result/{wildcards.sample}/{wildcards.sample}.chr20.unphased "
		"--mode unphased "
		"--nprocs 2 "
		"--reference_set {input.reference_set}/ "
		"--min_coverage 8 "
		"--min_MS_length 6 "
		"--flank_size 5 "
		"--rus 1 2 3 4 5 6 "

rule unphased_MSIprofiler_21:
	input:
		bam="bam_links_tumor/{sample}.tumor.bam",
		fasta="/storage/douyanmeiLab/lujinhong/tools/MSIprofiler/chrs_fa/",
		reference_set="/storage/douyanmeiLab/lujinhong/tools/MSIprofiler/reference_sets/"
	output:
		"result/{sample}/{sample}.chr21.unphased_unphased.txt"
	resources:
		mem_mb=12000
	shell:
		"python /storage/douyanmeiLab/lujinhong/tools/MSIprofiler/msi_profiler.py "
		"--tumor_bam {input.bam} "
		"--normal_bam bam_links_normal/{wildcards.sample}.normal.bam "
		"--bed None "
		"--chromosomes 21 "
		"--fasta {input.fasta}/ "
		"--output_prefix result/{wildcards.sample}/{wildcards.sample}.chr21.unphased "
		"--mode unphased "
		"--nprocs 2 "
		"--reference_set {input.reference_set}/ "
		"--min_coverage 8 "
		"--min_MS_length 6 "
		"--flank_size 5 "
		"--rus 1 2 3 4 5 6 "

rule unphased_MSIprofiler_22:
	input:
		bam="bam_links_tumor/{sample}.tumor.bam",
		fasta="/storage/douyanmeiLab/lujinhong/tools/MSIprofiler/chrs_fa/",
		reference_set="/storage/douyanmeiLab/lujinhong/tools/MSIprofiler/reference_sets/"
	output:
		"result/{sample}/{sample}.chr22.unphased_unphased.txt"
	resources:
		mem_mb=12000
	shell:
		"python /storage/douyanmeiLab/lujinhong/tools/MSIprofiler/msi_profiler.py "
		"--tumor_bam {input.bam} "
		"--normal_bam bam_links_normal/{wildcards.sample}.normal.bam "
		"--bed None "
		"--chromosomes 22 "
		"--fasta {input.fasta}/ "
		"--output_prefix result/{wildcards.sample}/{wildcards.sample}.chr22.unphased "
		"--mode unphased "
		"--nprocs 2 "
		"--reference_set {input.reference_set}/ "
		"--min_coverage 8 "
		"--min_MS_length 6 "
		"--flank_size 5 "
		"--rus 1 2 3 4 5 6 "

rule unphased_MSIprofiler_X:
	input:
		bam="bam_links_tumor/{sample}.tumor.bam",
		fasta="/storage/douyanmeiLab/lujinhong/tools/MSIprofiler/chrs_fa/",
		reference_set="/storage/douyanmeiLab/lujinhong/tools/MSIprofiler/reference_sets/"
	output:
		"result/{sample}/{sample}.chrX.unphased_unphased.txt"
	resources:
		mem_mb=12000
	shell:
		"python /storage/douyanmeiLab/lujinhong/tools/MSIprofiler/msi_profiler.py "
		"--tumor_bam {input.bam} "
		"--normal_bam bam_links_normal/{wildcards.sample}.normal.bam "
		"--bed None "
		"--chromosomes X "
		"--fasta {input.fasta}/ "
		"--output_prefix result/{wildcards.sample}/{wildcards.sample}.chrX.unphased "
		"--mode unphased "
		"--nprocs 2 "
		"--reference_set {input.reference_set}/ "
		"--min_coverage 8 "
		"--min_MS_length 6 "
		"--flank_size 5 "
		"--rus 1 2 3 4 5 6 "

rule unphased_MSIprofiler_Y:
	input:
		bam="bam_links_tumor/{sample}.tumor.bam",
		fasta="/storage/douyanmeiLab/lujinhong/tools/MSIprofiler/chrs_fa/",
		reference_set="/storage/douyanmeiLab/lujinhong/tools/MSIprofiler/reference_sets/"
	output:
		"result/{sample}/{sample}.chrY.unphased_unphased.txt"
	resources:
		mem_mb=12000
	shell:
		"python /storage/douyanmeiLab/lujinhong/tools/MSIprofiler/msi_profiler.py "
		"--tumor_bam {input.bam} "
		"--normal_bam bam_links_normal/{wildcards.sample}.normal.bam "
		"--bed None "
		"--chromosomes Y "
		"--fasta {input.fasta}/ "
		"--output_prefix result/{wildcards.sample}/{wildcards.sample}.chrY.unphased "
		"--mode unphased "
		"--nprocs 2 "
		"--reference_set {input.reference_set}/ "
		"--min_coverage 8 "
		"--min_MS_length 6 "
		"--flank_size 5 "
		"--rus 1 2 3 4 5 6 "


rule z_filterMSI:
	input:
		expand("result/{sample}/{sample}.chr{chr}.unphased_unphased.txt",sample=sample_IDs,chr=chrs)
	output:
		"MSI/{sample}.unphased_MSI.txt"
	resources:
		mem_mb=2000
	shell:
		"paste <(cat {input} | awk '$(NF-1)<0.01') "
		"<(cat result/{wildcards.sample}/{wildcards.sample}.chr*.unphased_unphased.txt  | awk '$(NF-1)<0.01{{print $8}}'|sed 's/,/ /g'| "
		"while read var; do echo $var|sed 's/ /\\n/g'|sort|uniq|wc -l;done)| "
		"awk '$NF<3' >> {output}"
