log <- file(snakemake@log[[1]], open="wt")
sink(log)
## set up packages
options(repos = c(CRAN = "http://cran.rstudio.com"))
if (!requireNamespace("pacman", quietly = TRUE))
  install.packages("pacman")
if (!requireNamespace("dndscv", quietly = TRUE))
  writeLines("fail", snakemake@output[[1]])
  pacman::p_load_gh("im3sanger/dndscv",ask = FALSE)
if (requireNamespace("dndscv", quietly = TRUE))
  print("ok")
  writeLines("ok", snakemake@output[[1]])